# Generated by Django 3.1.2 on 2020-10-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('oauth', '0002_auto_20201021_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
