# Generated by Django 3.1.2 on 2020-10-22 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0003_auto_20201021_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ipaddress',
            new_name='ip_address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
