# Generated by Django 3.1.2 on 2020-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20201021_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
