# Generated by Django 3.1.2 on 2020-10-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20201022_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ip',
            new_name='last_IP',
        ),
        migrations.AddField(
            model_name='profile',
            name='IPs',
            field=models.TextField(null=True),
        ),
    ]
